const $=s=>document.querySelector(s);const token=new URLSearchParams(location.search).get('token');let photos=[],selected=new Set(),event=null,selection=null,filter='all';const api='https://tjnjlximolahbbalpxgq.supabase.co/functions/v1/client-gallery-api';
async function call(action,extra={}){const r=await fetch(api,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,token,...extra})});const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||'Request failed');return j}
async function boot(){if(!token)return fail('חסר קישור גישה.');try{const j=await call('load');event=j.event;photos=j.photos||[];selection=j.selection||null;selected=new Set(j.selected_ids||[]);$('#cgTitle').textContent=event.title;$('#cgMeta').textContent=[event.event_type,event.event_date?new Date(event.event_date+'T00:00:00').toLocaleDateString('he-IL'):''].filter(Boolean).join(' · ');$('#cgLoading').hidden=true;$('#cgApp').hidden=false;render()}catch(e){fail(e.message)}}
function fail(msg){$('#cgLoading').hidden=true;$('#cgError').hidden=false;$('#cgErrorText').textContent=msg}
function render(){const max=event.max_selections;$('#cgSelected').textContent=selected.size;$('#cgLimit').textContent=max?`מתוך ${max} אפשריות`:'תמונות נבחרו';$('#cgStatus').textContent=selection?.status==='submitted'?'הבחירה נשלחה לצלם ✓':'לחצו על תמונה כדי לבחור';$('#cgSubmitBtn').disabled=selection?.status==='submitted';const arr=filter==='selected'?photos.filter(p=>selected.has(p.id)):photos;$('#cgGrid').innerHTML=arr.map(p=>`<button class="cg-photo ${selected.has(p.id)?'selected':''}" data-id="${p.id}" type="button"><img src="${p.preview_url}" alt="${p.original_filename||'תמונה מהאירוע'}" loading="lazy"><span class="cg-check">${selected.has(p.id)?'✓':'♡'}</span></button>`).join('');document.querySelectorAll('.cg-photo').forEach(b=>b.onclick=()=>toggle(b.dataset.id))}
async function toggle(id){if(selection?.status==='submitted')return;const wants=!selected.has(id);if(wants&&event.max_selections&&selected.size>=event.max_selections){$('#cgSubmitMsg').textContent=`אפשר לבחור עד ${event.max_selections} תמונות.`;return}if(wants)selected.add(id);else selected.delete(id);render();try{const j=await call('toggle',{photo_id:id,selected:wants});selection=j.selection||selection}catch(e){if(wants)selected.delete(id);else selected.add(id);render();$('#cgSubmitMsg').textContent='שמירת הבחירה נכשלה, נסו שוב.'}}
document.querySelectorAll('.cg-filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.cg-filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;render()});
$('#cgSubmitBtn').onclick=async()=>{if(!selected.size){$('#cgSubmitMsg').textContent='בחרו לפחות תמונה אחת.';return}if(!confirm(`לשלוח לצלם את הבחירה של ${selected.size} תמונות?`))return;$('#cgSubmitBtn').disabled=true;$('#cgSubmitBtn').textContent='שולח…';try{const j=await call('submit',{client_name:$('#cgName').value.trim(),client_email:$('#cgEmail').value.trim(),notes:$('#cgNotes').value.trim()});selection=j.selection;try{const adminUrl=new URL('admin/client-galleries.html',location.href);adminUrl.searchParams.set('event',event.id);await fetch('https://formsubmit.co/ajax/haimnetanelhatzalam@gmail.com',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({'אירוע':event.title,'מספר תמונות שנבחרו':selected.size,'שם הלקוח':$('#cgName').value.trim()||'לא צוין','אימייל לקוח':$('#cgEmail').value.trim()||'לא צוין','הערה':$('#cgNotes').value.trim()||'ללא הערה','קישור לניהול הבחירה':adminUrl.href,_subject:`בחירת תמונות חדשה - ${event.title}`,_template:'table',_captcha:'false'})})}catch{}$('#cgSubmitMsg').textContent='תודה! הבחירה התקבלה בהצלחה ✓';$('#cgSubmitBtn').textContent='הבחירה נשלחה';render()}catch(e){$('#cgSubmitBtn').disabled=false;$('#cgSubmitBtn').textContent='אישור ושליחת הבחירה';$('#cgSubmitMsg').textContent='השליחה נכשלה. נסו שוב.'}};
boot();
