(async function(){
 try{const r=await fetch('/content/site.json',{cache:'no-store'});if(!r.ok)return;const c=await r.json(),root=document.documentElement;
 const t=c.theme||{};root.style.setProperty('--hn-gold',t.goldColor||'#d6ad55');root.style.setProperty('--hn-text',t.textColor||'#f6f1e7');root.style.setProperty('--hn-bg',t.backgroundColor||'#080808');root.style.setProperty('--hn-panel',t.panelColor||'#111111');document.body.style.fontFamily=t.bodyFont||'Arial';document.body.style.backgroundColor=t.backgroundColor||'';document.querySelectorAll('h1,h2,h3,.brand span,.lux-name').forEach(e=>e.style.fontFamily=t.headingFont||'Georgia');document.querySelectorAll('.btn').forEach(e=>Object.assign(e.style,{borderRadius:(t.buttonRadius||12)+'px',borderWidth:(t.buttonBorderWidth||1)+'px',borderColor:t.buttonBorder||t.goldColor||'#d6ad55',boxShadow:`0 8px ${t.buttonShadow||16}px #0006`}));
 const id=x=>document.getElementById(x),txt=(x,v)=>{const e=id(x);if(e&&v!=null)e.textContent=v};txt('heroTitleWhite',c.hero?.title_white);txt('heroTitleGold',c.hero?.title_gold);txt('heroDescription',c.hero?.description);txt('aboutPreviewTitle',c.about?.title);txt('aboutPreviewText',c.about?.text);txt('areasText',c.areas);
 const hw=id('heroTitleWhite'),hg=id('heroTitleGold');if(hw&&c.typography?.heroWhite){const s=c.typography.heroWhite;Object.assign(hw.style,{fontFamily:s.font,fontSize:s.size+'px',fontWeight:s.weight,color:s.color,letterSpacing:(s.letterSpacing||0)+'px',lineHeight:s.lineHeight||1.15})}if(hg&&c.typography?.heroGold){const s=c.typography.heroGold;Object.assign(hg.style,{fontFamily:s.font,fontSize:s.size+'px',fontWeight:s.weight,color:s.color,letterSpacing:(s.letterSpacing||0)+'px',lineHeight:s.lineHeight||1.15})}
 if(c.hero?.image){const p=document.querySelector('.lux-hero-photo');if(p)p.style.backgroundImage=`url("${c.hero.image}")`}
 const pd=c.contact?.phone_display||'052-308-4940',pe=c.contact?.phone_e164||'+972523084940',wa=c.contact?.whatsapp||'972523084940';document.querySelectorAll('[data-phone-display]').forEach(e=>e.textContent=pd);document.querySelectorAll('a[data-phone-link]').forEach(e=>e.href='tel:'+pe);document.querySelectorAll('a[data-wa-link]').forEach(e=>e.href='https://wa.me/'+wa+(e.dataset.waText?'?text='+encodeURIComponent(e.dataset.waText):''));
 if(Array.isArray(c.services))document.querySelectorAll('.lux-service-item').forEach((e,i)=>{const s=c.services[i];if(!s)return;const a=e.querySelector('strong'),b=e.querySelector('small');if(a)a.textContent=s.title;if(b)b.textContent=s.subtitle});
 const grid=id('homeGalleryGrid');if(grid&&Array.isArray(c.gallery)){grid.innerHTML='';c.gallery.slice(0,8).forEach(g=>{const a=document.createElement('a');a.className='thumb';a.href='/gallery';const im=document.createElement('img');im.src=g.image;im.alt=g.alt||g.title||'';im.loading='lazy';const s=g.style||{};Object.assign(im.style,{border:`${s.borderWidth||0}px solid ${s.borderColor||'transparent'}`,borderRadius:(s.radius||0)+'px',boxShadow:`0 ${Math.round((s.shadow||0)/2)}px ${s.shadow||0}px #0008`,filter:`brightness(${s.brightness||100}%) contrast(${s.contrast||100}%) saturate(${s.saturation||100}%) grayscale(${s.grayscale||0}%)`,transform:`scale(${(s.zoom||100)/100})`});const sp=document.createElement('span');sp.textContent=g.title||'';a.append(im,sp);grid.appendChild(a)})}
 const path=location.pathname;let seo=path.includes('gallery')?c.seo?.gallery:c.seo?.home;if(seo){if(seo.title)document.title=seo.title;let m=document.querySelector('meta[name=description]');if(m&&seo.description)m.content=seo.description}
 }catch(e){console.warn('HN CMS skipped',e)}
})();
