(() => {
 const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
 const loginScreen=$('#loginScreen'),app=$('#app'),toast=$('#toast'); let user=null,content=null,fileSha=null,currentUploadTarget=null,editIndex=null,activeCategory='all';
 const gateway='/.netlify/git/github', contentPath='content/site.json';
 const defaults={theme:{bodyFont:'Arial',headingFont:'Georgia',textColor:'#f6f1e7',mutedColor:'#bdb5a7',goldColor:'#d6ad55',backgroundColor:'#080808',panelColor:'#111111',buttonRadius:12,sectionSpacing:72},typography:{heroWhite:{font:'Arial',size:64,weight:700,color:'#ffffff',letterSpacing:0},heroGold:{font:'Georgia',size:64,weight:700,color:'#d6ad55',letterSpacing:0}},pages:{home:{enabled:true,sections:['hero','preview','cta']},about:{enabled:true},services:{enabled:true},gallery:{enabled:true},areas:{enabled:true},reviews:{enabled:true},contact:{enabled:true}},seo:{home:{title:'',description:'',ogImage:''},gallery:{title:'',description:'',ogImage:''}},activity:[],categories:[]};
 const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;');
 function toastMsg(m,e=false){toast.textContent=m;toast.className='toast show'+(e?' error':'');setTimeout(()=>toast.className='toast',3200)} function loading(v){app.classList.toggle('loading',v)}
 async function headers(){const token=await user.jwt();return {Authorization:`Bearer ${token}`,'Content-Type':'application/json'}}
 function b64d(str){const bin=atob(str.replace(/\n/g,'')),bytes=Uint8Array.from(bin,c=>c.charCodeAt(0));return new TextDecoder().decode(bytes)} function b64e(str){const bytes=new TextEncoder().encode(str);let bin='';bytes.forEach(b=>bin+=String.fromCharCode(b));return btoa(bin)}
 function normalize(){content.theme={...defaults.theme,...content.theme};content.typography={...defaults.typography,...content.typography,heroWhite:{...defaults.typography.heroWhite,...content.typography?.heroWhite},heroGold:{...defaults.typography.heroGold,...content.typography?.heroGold}};content.pages={...defaults.pages,...content.pages};content.seo={home:{...defaults.seo.home,...content.seo?.home},gallery:{...defaults.seo.gallery,...content.seo?.gallery}};content.activity=Array.isArray(content.activity)?content.activity:[];content.gallery=Array.isArray(content.gallery)?content.gallery:[];content.categories=Array.isArray(content.categories)&&content.categories.length?content.categories:[...new Set(content.gallery.map(x=>x.category||x.title).filter(Boolean))];content.gallery.forEach(g=>{g.category=g.category||g.title||'כללי';g.style={borderColor:'#d6ad55',borderWidth:0,radius:12,shadow:12,brightness:100,contrast:100,saturation:100,grayscale:0,zoom:100,...g.style}})}
 async function load(){loading(true);try{const r=await fetch(`${gateway}/contents/${contentPath}?ref=main`,{headers:await headers()});if(!r.ok)throw Error(`טעינה נכשלה (${r.status})`);const j=await r.json();fileSha=j.sha;content=JSON.parse(b64d(j.content));normalize();fill()}catch(e){toastMsg(e.message,true)}finally{loading(false)}}
 function fill(){ $('#heroWhite').value=content.hero?.title_white||'';$('#heroGold').value=content.hero?.title_gold||'';$('#heroDescription').value=content.hero?.description||'';$('#heroImage').value=content.hero?.image||'';$('#heroPreview').src=content.hero?.image||'';$('#aboutTitle').value=content.about?.title||'';$('#aboutText').value=content.about?.text||'';$('#phoneDisplay').value=content.contact?.phone_display||'';$('#phoneE164').value=content.contact?.phone_e164||'';$('#whatsapp').value=content.contact?.whatsapp||'';$('#areasText').value=content.areas||''; renderServices();renderGallery();fillDesign();fillSeo();renderPages();renderActivity();updateStats() }
 function collect(){content.hero={title_white:$('#heroWhite').value.trim(),title_gold:$('#heroGold').value.trim(),description:$('#heroDescription').value.trim(),image:$('#heroImage').value.trim()};content.about={title:$('#aboutTitle').value.trim(),text:$('#aboutText').value.trim()};content.contact={phone_display:$('#phoneDisplay').value.trim(),phone_e164:$('#phoneE164').value.trim(),whatsapp:$('#whatsapp').value.trim()};content.areas=$('#areasText').value.trim();content.services=$$('.service-row').map(r=>({title:r.querySelector('[data-s-title]').value.trim(),subtitle:r.querySelector('[data-s-sub]').value.trim()}));collectDesign();collectSeo()}
 async function save(){collect();content.activity.unshift({text:'תוכן האתר עודכן דרך HN Admin Studio',time:new Date().toISOString()});content.activity=content.activity.slice(0,20);loading(true);try{const body={message:'Update from HN Admin Studio V9',content:b64e(JSON.stringify(content,null,2)),branch:'main',sha:fileSha};const r=await fetch(`${gateway}/contents/${contentPath}`,{method:'PUT',headers:await headers(),body:JSON.stringify(body)});if(!r.ok)throw Error(`שמירה נכשלה (${r.status})`);const j=await r.json();fileSha=j.content?.sha||fileSha;renderActivity();updateStats();toastMsg('נשמר ✓ Netlify יעדכן את האתר אוטומטית')}catch(e){toastMsg(e.message,true)}finally{loading(false)}}
 function renderServices(){const p=$('#servicesPanel');p.innerHTML='<div class="form-grid">'+(content.services||[]).map((s,i)=>`<div class="panel service-row" style="margin:0;padding:16px"><h3 style="margin-top:0;color:#d6ad55">שירות ${i+1}</h3><div class="field"><label>שם השירות</label><input data-s-title value="${esc(s.title)}"></div><br><div class="field"><label>שורת משנה</label><input data-s-sub value="${esc(s.subtitle)}"></div></div>`).join('')+'</div>'}
 function imgCss(s){return `border:${s.borderWidth}px solid ${s.borderColor};border-radius:${s.radius}px;box-shadow:0 ${Math.round(s.shadow/2)}px ${s.shadow}px #0008;filter:brightness(${s.brightness}%) contrast(${s.contrast}%) saturate(${s.saturation}%) grayscale(${s.grayscale}%);transform:scale(${s.zoom/100})`}
 function renderGallery(){const list=$('#galleryList');list.innerHTML='';const cats=['all',...content.categories];$('#categoryFilters').innerHTML=cats.map(c=>`<button class="filter-pill ${activeCategory===c?'active':''}" data-cat="${esc(c)}">${c==='all'?'הכול':esc(c)}</button>`).join('');$('#galleryCategoryFilter').innerHTML=cats.map(c=>`<option value="${esc(c)}">${c==='all'?'כל הקטגוריות':esc(c)}</option>`).join('');$('#galleryCategoryFilter').value=activeCategory;content.gallery.forEach((g,i)=>{if(activeCategory!=='all'&&g.category!==activeCategory)return;const el=document.createElement('div');el.className='gallery-item';el.innerHTML=`${g.cover?'<span class="cover-flag">COVER</span>':''}<div style="overflow:hidden"><img src="${esc(g.image)}" style="${imgCss(g.style)}"></div><div class="gallery-item-body"><b>${esc(g.title||'ללא כותרת')}</b><div style="color:#9f978b;font-size:12px;margin:5px 0 10px">${esc(g.category)}</div><div class="gallery-actions"><div class="order-actions"><button class="mini-btn" data-up="${i}">↑</button><button class="mini-btn" data-down="${i}">↓</button></div><div><button class="mini-btn" data-edit="${i}">עריכה</button> <button class="mini-btn mini-danger" data-del="${i}">מחיקה</button></div></div></div>`;list.appendChild(el)});$$('[data-cat]').forEach(b=>b.onclick=()=>{activeCategory=b.dataset.cat;renderGallery()});$$('[data-edit]').forEach(b=>b.onclick=()=>openEditor(+b.dataset.edit));$$('[data-del]').forEach(b=>b.onclick=()=>{if(confirm('למחוק את התמונה מהגלריה?')){content.gallery.splice(+b.dataset.del,1);renderGallery();updateStats()}});$$('[data-up]').forEach(b=>b.onclick=()=>move(+b.dataset.up,-1));$$('[data-down]').forEach(b=>b.onclick=()=>move(+b.dataset.down,1))}
 function move(i,d){const j=i+d;if(j<0||j>=content.gallery.length)return;[content.gallery[i],content.gallery[j]]=[content.gallery[j],content.gallery[i]];renderGallery()}
 function openEditor(i){editIndex=i;const g=content.gallery[i],s=g.style;$('#editCategory').innerHTML=content.categories.map(c=>`<option>${esc(c)}</option>`).join('');$('#editCategory').value=g.category;$('#editTitle').value=g.title||'';$('#editAlt').value=g.alt||'';$('#editCover').checked=!!g.cover;['BorderColor','BorderWidth','Radius','Shadow','Brightness','Contrast','Saturation','Grayscale','Zoom'].forEach(k=>$('#edit'+k).value=s[k[0].toLowerCase()+k.slice(1)]);$('#editorPreview').src=g.image;updateEditorPreview();$('#imageEditor').classList.add('open')}
 function updateEditorPreview(){if(editIndex==null)return;const s={borderColor:$('#editBorderColor').value,borderWidth:+$('#editBorderWidth').value,radius:+$('#editRadius').value,shadow:+$('#editShadow').value,brightness:+$('#editBrightness').value,contrast:+$('#editContrast').value,saturation:+$('#editSaturation').value,grayscale:+$('#editGrayscale').value,zoom:+$('#editZoom').value};$('#editorPreview').style.cssText=imgCss(s)}
 function applyEditor(){const g=content.gallery[editIndex];g.category=$('#editCategory').value;g.title=$('#editTitle').value;g.alt=$('#editAlt').value;g.cover=$('#editCover').checked;if(g.cover)content.gallery.forEach((x,i)=>{if(i!==editIndex&&x.category===g.category)x.cover=false});g.style={borderColor:$('#editBorderColor').value,borderWidth:+$('#editBorderWidth').value,radius:+$('#editRadius').value,shadow:+$('#editShadow').value,brightness:+$('#editBrightness').value,contrast:+$('#editContrast').value,saturation:+$('#editSaturation').value,grayscale:+$('#editGrayscale').value,zoom:+$('#editZoom').value};$('#imageEditor').classList.remove('open');renderGallery();toastMsg('עריכת התמונה מוכנה — לחץ שמירה כדי לפרסם')}
 function addCategory(){const n=prompt('שם הקטגוריה החדשה:');if(!n)return;if(!content.categories.includes(n.trim()))content.categories.push(n.trim());renderGallery();updateStats()}
 async function upload(files){if(!files?.length)return;loading(true);try{for(const file of files){const ext=(file.name.split('.').pop()||'jpg').replace(/[^a-z0-9]/gi,'').toLowerCase(),name=`${Date.now()}-${Math.random().toString(36).slice(2,7)}.${ext}`,path=`assets/uploads/${name}`,arr=new Uint8Array(await file.arrayBuffer());let bin='';arr.forEach(b=>bin+=String.fromCharCode(b));const r=await fetch(`${gateway}/contents/${path}`,{method:'PUT',headers:await headers(),body:JSON.stringify({message:`Upload ${name}`,content:btoa(bin),branch:'main'})});if(!r.ok)throw Error(`העלאה נכשלה (${r.status})`);const publicPath='/'+path;if(currentUploadTarget==='hero'){$('#heroImage').value=publicPath;$('#heroPreview').src=publicPath}else{const cat=activeCategory==='all'?(content.categories[0]||'כללי'):activeCategory;content.gallery.push({title:file.name.replace(/\.[^.]+$/,''),category:cat,image:publicPath,alt:'',cover:false,style:{borderColor:'#d6ad55',borderWidth:0,radius:12,shadow:12,brightness:100,contrast:100,saturation:100,grayscale:0,zoom:100}})}}renderGallery();updateStats();toastMsg('התמונות הועלו ✓ לחץ שמירת הגלריה לפרסום')}catch(e){toastMsg(e.message,true)}finally{loading(false);currentUploadTarget=null;$('#hiddenFile').value=''}}
 function fillDesign(){const t=content.theme,ty=content.typography;['bodyFont','headingFont','textColor','goldColor','backgroundColor','panelColor','buttonRadius','sectionSpacing'].forEach(k=>$('#'+k).value=t[k]);$('#heroWhiteFont').value=ty.heroWhite.font;$('#heroWhiteColor').value=ty.heroWhite.color;$('#heroWhiteSize').value=ty.heroWhite.size;$('#heroWhiteWeight').value=ty.heroWhite.weight;$('#heroGoldFont').value=ty.heroGold.font;$('#heroGoldColor').value=ty.heroGold.color;$('#heroGoldSize').value=ty.heroGold.size;$('#heroGoldWeight').value=ty.heroGold.weight;rangeLabels()}
 function collectDesign(){const t=content.theme;['bodyFont','headingFont','textColor','goldColor','backgroundColor','panelColor'].forEach(k=>t[k]=$('#'+k).value);t.buttonRadius=+$('#buttonRadius').value;t.sectionSpacing=+$('#sectionSpacing').value;content.typography.heroWhite={...content.typography.heroWhite,font:$('#heroWhiteFont').value,color:$('#heroWhiteColor').value,size:+$('#heroWhiteSize').value,weight:+$('#heroWhiteWeight').value};content.typography.heroGold={...content.typography.heroGold,font:$('#heroGoldFont').value,color:$('#heroGoldColor').value,size:+$('#heroGoldSize').value,weight:+$('#heroGoldWeight').value}}
 function rangeLabels(){$('#radiusVal').textContent=$('#buttonRadius').value+'px';$('#spacingVal').textContent=$('#sectionSpacing').value+'px';$('#heroWhiteSizeVal').textContent=$('#heroWhiteSize').value+'px';$('#heroGoldSizeVal').textContent=$('#heroGoldSize').value+'px'}
 function fillSeo(){$('#seoHomeTitle').value=content.seo.home.title;$('#seoHomeDescription').value=content.seo.home.description;$('#seoHomeOg').value=content.seo.home.ogImage;$('#seoGalleryTitle').value=content.seo.gallery.title;$('#seoGalleryDescription').value=content.seo.gallery.description}
 function collectSeo(){content.seo.home={...content.seo.home,title:$('#seoHomeTitle').value,description:$('#seoHomeDescription').value,ogImage:$('#seoHomeOg').value};content.seo.gallery={...content.seo.gallery,title:$('#seoGalleryTitle').value,description:$('#seoGalleryDescription').value}}
 function renderPages(){const names={home:'דף הבית',about:'אודות',services:'שירותים',gallery:'גלריה',areas:'אזורי שירות',reviews:'המלצות',contact:'יצירת קשר'};$('#pageControls').innerHTML=Object.entries(names).map(([k,n])=>`<label class="page-toggle"><span>${n}</span><input type="checkbox" data-page="${k}" ${content.pages[k]?.enabled!==false?'checked':''}></label>`).join('');$$('[data-page]').forEach(x=>x.onchange=()=>{content.pages[x.dataset.page]={...content.pages[x.dataset.page],enabled:x.checked}})}
 function renderActivity(){const arr=content.activity||[],html=arr.length?arr.map(a=>`<div class="activity-item"><b>${esc(a.text)}</b><span>${new Date(a.time).toLocaleString('he-IL')}</span></div>`).join(''):'<div class="note">עדיין אין פעילות שמורה. השמירה הבאה תופיע כאן.</div>';$('#activityList').innerHTML=html;$('#dashboardActivity').innerHTML=arr.slice(0,4).map(a=>`<div class="activity-item"><b>${esc(a.text)}</b><span>${new Date(a.time).toLocaleString('he-IL')}</span></div>`).join('')||'<span class="note">אין פעילות עדיין</span>'}
 function updateStats(){$('#statGallery').textContent=content.gallery.length;$('#statCategories').textContent=content.categories.length;$('#statUpdated').textContent=content.activity?.[0]?new Date(content.activity[0].time).toLocaleDateString('he-IL'):'—'}
 function openSection(n){$$('.section').forEach(s=>s.classList.toggle('active',s.id===`section-${n}`));$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.section===n));const l={dashboard:'לוח בקרה',home:'דף הבית',gallery:'גלריה ותמונות',about:'אודות',services:'שירותים',areas:'אזורי שירות',contact:'יצירת קשר',design:'עיצוב האתר',seo:'SEO ונתונים',activity:'פעילות אחרונה',future:'אזור לקוחות'};$('#pageTitle').textContent=l[n]||'מרכז ניהול';$('#sidebar').classList.remove('open');scrollTo({top:0,behavior:'smooth'})}
 function start(u){user=u;loginScreen.style.display='none';app.classList.add('ready');$('#userEmail').textContent=u.email||'';load()}
 $('#loginBtn').onclick=()=>netlifyIdentity?.open('login');$('#logoutBtn').onclick=()=>netlifyIdentity?.logout();$('#mobileMenu').onclick=()=>$('#sidebar').classList.toggle('open');$$('.nav-btn').forEach(b=>b.onclick=()=>openSection(b.dataset.section));$$('[data-open]').forEach(b=>b.onclick=()=>openSection(b.dataset.open));$$('.save-btn').forEach(b=>b.onclick=save);$$('.reload-btn').forEach(b=>b.onclick=load);$('#addCategory').onclick=addCategory;$('#addGallery').onclick=()=>{currentUploadTarget='gallery';$('#hiddenFile').click()};$$('[data-upload-target]').forEach(b=>b.onclick=()=>{currentUploadTarget='hero';$('#hiddenFile').click()});$('#hiddenFile').onchange=e=>upload([...e.target.files]);$('#galleryCategoryFilter').onchange=e=>{activeCategory=e.target.value;renderGallery()};$('#closeImageEditor').onclick=()=>$('#imageEditor').classList.remove('open');$('#applyImageEdit').onclick=applyEditor;$$('#imageEditor input[type=range],#imageEditor input[type=color]').forEach(x=>x.oninput=updateEditorPreview);$$('#buttonRadius,#sectionSpacing,#heroWhiteSize,#heroGoldSize').forEach(x=>x.oninput=rangeLabels);$('#openPreview').onclick=()=>window.open('/','_blank');$('#resetTheme').onclick=()=>{content.theme={...defaults.theme};content.typography={...defaults.typography,heroWhite:{...defaults.typography.heroWhite},heroGold:{...defaults.typography.heroGold}};fillDesign();toastMsg('Theme אופס — לחץ שמירה כדי לפרסם')};$('#quickAdd').onclick=()=>$('#quickModal').classList.add('open');$('#closeQuick').onclick=()=>$('#quickModal').classList.remove('open');$$('[data-quick]').forEach(b=>b.onclick=()=>{const q=b.dataset.quick;$('#quickModal').classList.remove('open');if(q==='upload'){openSection('gallery');currentUploadTarget='gallery';$('#hiddenFile').click()}if(q==='category'){openSection('gallery');addCategory()}if(q==='home')openSection('home')});
 if(window.netlifyIdentity){netlifyIdentity.on('init',u=>u&&start(u));netlifyIdentity.on('login',u=>{netlifyIdentity.close();start(u)});netlifyIdentity.on('logout',()=>location.reload());netlifyIdentity.init()}
})();
